const testData = {
  chats: [],
  districtsDeck: [
    {
      districtName: "Manor",
      cost: "3",
      value: "3",
      type: "yellow",
      id: "3906bd64-90ff-4b35-980e-a89838d6c7cf",
    },
    {
      districtName: "Manor",
      cost: "3",
      value: "3",
      type: "yellow",
      id: "6f5cd0dc-aaf9-4093-aff5-e9585d554b98",
    },
    {
      districtName: "Temple",
      cost: "1",
      value: "1",
      type: "blue",
      id: "1519ea21-88fa-4198-92ae-f8bc4cc9ebb3",
    },
    {
      districtName: "Monastery",
      cost: "3",
      value: "3",
      type: "blue",
      id: "ac7e5f7d-2205-4fd7-8707-aeaa3a22e349",
    },
    {
      districtName: "Docks",
      cost: "3",
      value: "3",
      type: "green",
      id: "26bab028-bc80-4f3a-bf91-5b34cdacb443",
    },
    {
      districtName: "Tavern",
      cost: "1",
      value: "1",
      type: "green",
      id: "5f07be07-208a-4f2d-aa09-7b96772f53a1",
    },
    {
      districtName: "Castle",
      cost: "4",
      value: "4",
      type: "yellow",
      id: "dcf528fc-3f9d-455b-b4d2-1429719549ed",
    },
    {
      districtName: "Monastery",
      cost: "3",
      value: "3",
      type: "blue",
      id: "fe0f7bd8-8d5c-46bd-b5ba-310738a95d1f",
    },
    {
      districtName: "Harbor",
      cost: "4",
      value: "4",
      type: "green",
      id: "e213f119-c85f-4eec-a24c-600f9b80fd75",
    },
    {
      districtName: "Temple",
      cost: "1",
      value: "1",
      type: "blue",
      id: "ea64900b-5749-48bd-abcb-212e138a9127",
    },
    {
      districtName: "Palace",
      cost: "5",
      value: "5",
      type: "yellow",
      id: "87f2e896-1b2d-44a9-8004-f5f7b025289e",
    },
    {
      districtName: "Market",
      cost: "2",
      value: "2",
      type: "green",
      id: "0d2331a9-a5a6-4805-9773-ec203c84a32c",
    },
    {
      districtName: "Battlefield",
      cost: "3",
      value: "3",
      type: "red",
      id: "456360f6-55fb-4c78-acb2-c16a28101e94",
    },
    {
      districtName: "Haunted City",
      cost: "2",
      value: "2",
      type: "purple",
      uniqueDescription:
        "For purposes of Victory Points (not Income), the Haunted City is considered to be of any 1 color of your choice at the end of the game (unless you built it during the last round of the game).",
      abilityUsed: false,
      id: "2bc06488-f399-46a2-afc4-3b0a01b5ec24",
    },
    {
      districtName: "Church",
      cost: "2",
      value: "2",
      type: "blue",
      id: "0edee472-4657-45ad-95a5-853ff8119495",
    },
    {
      districtName: "Castle",
      cost: "4",
      value: "4",
      type: "yellow",
      id: "67e1bf6f-3389-46fe-8719-9554216a85af",
    },
    {
      districtName: "Trading Post",
      cost: "2",
      value: "2",
      type: "green",
      id: "b6c12617-8c0c-4fb9-860d-2149bb234adc",
    },
    {
      districtName: "Manor",
      cost: "3",
      value: "3",
      type: "yellow",
      id: "696c98bb-e40b-43ca-b6fe-8119df120495",
    },
    {
      districtName: "Trading Post",
      cost: "2",
      value: "2",
      type: "green",
      id: "909b702d-f9e0-435c-baf0-5ae6b063cb07",
    },
    {
      districtName: "Tavern",
      cost: "1",
      value: "1",
      type: "green",
      id: "4299aab8-ce46-4c01-a08c-4893f3b9400f",
    },
    {
      districtName: "Tavern",
      cost: "1",
      value: "1",
      type: "green",
      id: "e17d0b86-f663-4a86-8302-4b920876dc25",
    },
    {
      districtName: "Church",
      cost: "2",
      value: "2",
      type: "blue",
      id: "da61332b-e5ab-4c07-8438-61ca4f5cd5a1",
    },
    {
      districtName: "Manor",
      cost: "3",
      value: "3",
      type: "yellow",
      id: "1b2c5400-e75b-482c-863c-2bf3954afc40",
    },
    {
      districtName: "Palace",
      cost: "5",
      value: "5",
      type: "yellow",
      id: "11d4d63c-a322-435b-b68a-1d97edd081d6",
    },
    {
      districtName: "Harbor",
      cost: "4",
      value: "4",
      type: "green",
      id: "d9fd814f-2bbf-4020-a9b1-4450fe27e6ff",
    },
    {
      districtName: "Docks",
      cost: "3",
      value: "3",
      type: "green",
      id: "402fafcd-199f-4ef7-969b-0ccb6c188221",
    },
    {
      districtName: "Great Wall",
      cost: "6",
      value: "6",
      type: "purple",
      uniqueDescription:
        "The cost for the Warlord's /Diplomat's ability when targeting your districts (excluding the Great Wall) is increased by 1 gold.",
      abilityUsed: false,
      id: "1ab6e213-f95a-4252-affa-0d1dfc1ec1c9",
    },
    {
      districtName: "Cathedral",
      cost: "5",
      value: "5",
      type: "blue",
      id: "616a3fd9-106a-42c9-a3b0-8e5c6682b0a2",
    },
    {
      districtName: "Monastery",
      cost: "3",
      value: "3",
      type: "blue",
      id: "f3b56be3-ece2-4292-954d-ad41b01a30be",
    },
    {
      districtName: "Castle",
      cost: "4",
      value: "4",
      type: "yellow",
      id: "b0723d5d-735f-4b34-bdf0-9691aa970268",
    },
    {
      districtName: "Dragon Gate",
      cost: "8",
      value: "8",
      type: "purple",
      abilityUsed: false,
      id: "12a32370-ca23-4a40-8bf2-494f8ad2df79",
    },
    {
      districtName: "Manor",
      cost: "3",
      value: "3",
      type: "yellow",
      id: "1a296fad-4d5f-4011-9e06-5c4c626e6756",
    },
    {
      districtName: "Cathedral",
      cost: "5",
      value: "5",
      type: "blue",
      id: "962a83c2-50b2-47a0-a9dc-4338b3637e7f",
    },
    {
      districtName: "Battlefield",
      cost: "3",
      value: "3",
      type: "red",
      id: "cf454231-b7ab-49bf-9cd0-18229cd84dca",
    },
    {
      districtName: "Watchtower",
      cost: "1",
      value: "1",
      type: "red",
      id: "c09c8bd4-a057-4467-968a-1b0b11a7a5a2",
    },
    {
      districtName: "Battlefield",
      cost: "3",
      value: "3",
      type: "red",
      id: "4e560c15-6eb0-4938-b7d3-9f1b591f4981",
    },
    {
      districtName: "Market",
      cost: "2",
      value: "2",
      type: "green",
      id: "c1664996-125e-4536-8e8e-58b33b63c11d",
    },
    {
      districtName: "Prison",
      cost: "2",
      value: "2",
      type: "red",
      id: "9edcc23a-14bf-45b1-ba96-7bf119153086",
    },
    {
      districtName: "School of Magic",
      cost: "6",
      value: "6",
      type: "purple",
      uniqueDescription:
        "For purposes of Income (not Victory Points), the School of Magic is considered to be a color of your choice every turn.",
      abilityUsed: false,
      id: "bd532222-4348-4cab-90ef-194f7b7a8224",
    },
    {
      districtName: "Tavern",
      cost: "1",
      value: "1",
      type: "green",
      id: "24e2c9ae-7a16-4a75-834d-ec052c8aaa03",
    },
    {
      districtName: "Observatory",
      cost: "5",
      value: "5",
      type: "purple",
      uniqueDescription:
        "If you choose to draw cards when you take an action, you must draw an extra card and put an extra card on the bottom of the District Deck face-down in any order.",
      abilityUsed: false,
      id: "b5180642-8da1-4596-836a-3abc89450b20",
    },
    {
      districtName: "Palace",
      cost: "5",
      value: "5",
      type: "yellow",
      id: "a59f4229-925c-4b98-8dec-a011de3559ee",
    },
    {
      districtName: "Market",
      cost: "2",
      value: "2",
      type: "green",
      id: "f5482619-4af7-48b7-80ea-56580d0d6f2a",
    },
    {
      districtName: "Temple",
      cost: "1",
      value: "1",
      type: "blue",
      id: "c9e777ff-223c-4952-8f23-5781d641f511",
    },
    {
      districtName: "University",
      cost: "6",
      value: "6",
      type: "purple",
      uniqueDescription:
        "The cost for this district is 6, but is worth 8 Victory Points at the end of the game. The cost of the Warlord's Diplomat's ability targeting this district is based off the final cost of this district.",
      abilityUsed: false,
      id: "b0843460-96b8-45cc-aa73-cb411272bab3",
    },
    {
      districtName: "Town Hall",
      cost: "5",
      value: "5",
      type: "green",
      id: "ff822c39-587b-4c4d-8e69-a6e6446dd017",
    },
    {
      districtName: "Town Hall",
      cost: "5",
      value: "5",
      type: "green",
      id: "0da8bf0c-547e-4365-8950-49f9a209742c",
    },
    {
      districtName: "Keep",
      cost: "3",
      value: "3",
      type: "purple",
      uniqueDescription:
        "The Keep cannot be targeted by the Warlord's / Diplomat's ability.",
      abilityUsed: false,
      id: "e99d353c-f79a-413d-84a5-6263e6696dc4",
    },
    {
      districtName: "Castle",
      cost: "4",
      value: "4",
      type: "yellow",
      id: "8e19d49c-840e-4779-abbd-fa9a7ee63cd0",
    },
    {
      districtName: "Watchtower",
      cost: "1",
      value: "1",
      type: "red",
      id: "5a9ee77b-cfe4-4c18-9ea8-484c6838daee",
    },
    {
      districtName: "Keep",
      cost: "3",
      value: "3",
      type: "purple",
      uniqueDescription:
        "The Keep cannot be targeted by the Warlord's / Diplomat's ability.",
      abilityUsed: false,
      id: "b6ea107f-d5e1-4665-8079-963d7f0ffb03",
    },
    {
      districtName: "Prison",
      cost: "2",
      value: "2",
      type: "red",
      id: "9a543d93-182d-4e45-9b30-cfd3333d871e",
    },
    {
      districtName: "Tavern",
      cost: "1",
      value: "1",
      type: "green",
      id: "8ae23307-4455-4e8b-92e3-ceb8cf1dd737",
    },
    {
      districtName: "Graveyard",
      cost: "5",
      value: "5",
      type: "purple",
      uniqueDescription:
        "When the Warlord destroys a district (excluding the Graveyard) with his ability, you may pay 1 gold to put the destroyed district into your hand (unless you are the Warlord).Note: If the Diplomat is used, remove this card from the game and randomly replace it with another card.",
      abilityUsed: false,
      id: "660ccfb5-e82f-4ffc-8ccf-0838edf65b7b",
    },
    {
      districtName: "Laboratory",
      cost: "5",
      value: "5",
      type: "purple",
      uniqueDescription:
        "Once during your turn, you may put a district card from your hand to the bottom of the District Deck face-down and receive 1 gold from the bank.",
      abilityUsed: false,
      id: "fb65b3f2-73cc-402b-84da-7669e1ba7438",
    },
    {
      districtName: "Docks",
      cost: "3",
      value: "3",
      type: "green",
      id: "a314787d-bcfa-44a1-aba9-b5f42687a7ea",
    },
    {
      districtName: "Market",
      cost: "2",
      value: "2",
      type: "green",
      id: "21223f31-192b-453f-9af6-5b0cd13a1652",
    },
    {
      districtName: "Fortress",
      cost: "5",
      value: "5",
      type: "red",
      id: "7968a35f-d642-40ce-b001-4c2efabd7a11",
    },
  ],
  charactersDeck: [
    {
      name: "Thief",
      value: 2,
      jobDescription: "Steal From 1",
      drafted: true,
      burned: false,
      isFaceUp: false,
    },
    {
      name: "Magician",
      value: 3,
      jobDescription: "Trade Cards",
      drafted: true,
      burned: false,
      isFaceUp: false,
    },
    {
      name: "King",
      value: 4,
      jobDescription: "Get Crown",
      drafted: false,
      burned: false,
      isFaceUp: false,
    },
    {
      name: "Bishop",
      value: 5,
      jobDescription: "Get Money from RD",
      drafted: false,
      burned: false,
      isFaceUp: false,
    },
    {
      name: "Merchant",
      value: 6,
      jobDescription: "Get Money from TD",
      drafted: false,
      burned: false,
      isFaceUp: false,
    },
    {
      name: "Architect",
      value: 7,
      jobDescription: "Extra cards and builds",
      drafted: false,
      burned: false,
      isFaceUp: false,
    },
    {
      name: "Warlord",
      value: 8,
      jobDescription: "Destroy 1",
      drafted: false,
      burned: false,
      isFaceUp: false,
    },
  ],
  players: [
    {
      userName: "vqxrs",
      cards: [
        {
          districtName: "Trading Post",
          cost: "2",
          value: "2",
          type: "green",
          id: "5c5a9571-678c-4d2d-a101-4080ac7d3cef",
        },
        {
          districtName: "Harbor",
          cost: "4",
          value: "4",
          type: "green",
          id: "17138309-3dd0-45a4-8362-ea90e85c1eea",
        },
        {
          districtName: "Fortress",
          cost: "5",
          value: "5",
          type: "red",
          id: "c5069cda-aae6-44a0-8ef6-136d6291b785",
        },
        {
          districtName: "Prison",
          cost: "2",
          value: "2",
          type: "red",
          id: "d1c75181-645e-49b7-9957-919ba2781465",
        },
      ],
      character: {
        name: "Thief",
        value: 2,
        jobDescription: "Steal From 1",
        drafted: true,
        burned: false,
        isFaceUp: false,
      },
      districts: [],
      gold: 4,
      isAlive: true,
      isHost: true,
      isMarkedForTheft: false,
      isKing: false,
      id: "d8ZSvTzfstJVAmhVAAAJ",
      originalIndex: 0,
    },
    {
      userName: "sgsqn",
      cards: [
        {
          districtName: "Smithy",
          cost: "5",
          value: "5",
          type: "purple",
          uniqueDescription:
            "Once during your turn, you may pay 2 gold to draw 3 district cards.",
          abilityUsed: false,
          id: "e7d79ba9-cedb-4ee3-8c15-0411ad63c3b4",
        },
        {
          districtName: "Library",
          cost: "6",
          value: "6",
          type: "purple",
          uniqueDescription:
            "If you choose to draw cards when you take an action, you must keep an extra card you have drawn.",
          abilityUsed: false,
          id: "757f11c5-c290-492d-b715-a88a5d1c0535",
        },
        {
          districtName: "Watchtower",
          cost: "1",
          value: "1",
          type: "red",
          id: "31c14f5d-8706-401b-b846-32ec90fd3500",
        },
        {
          districtName: "Church",
          cost: "2",
          value: "2",
          type: "blue",
          id: "d1065675-1968-41df-87f6-e4e674f71ceb",
        },
      ],
      character: {
        name: "Magician",
        value: 3,
        jobDescription: "Trade Cards",
        drafted: true,
        burned: false,
        isFaceUp: false,
      },
      districts: [],
      gold: 2,
      isAlive: true,
      isHost: false,
      isMarkedForTheft: false,
      isKing: false,
      id: "wdG29YwhvUTQVuEWAAAL",
      originalIndex: 1,
    },
  ],
  initOrderOfPlayers: [
    {
      userName: "vqxrs",
      cards: [
        {
          districtName: "Trading Post",
          cost: "2",
          value: "2",
          type: "green",
          id: "5c5a9571-678c-4d2d-a101-4080ac7d3cef",
        },
        {
          districtName: "Harbor",
          cost: "4",
          value: "4",
          type: "green",
          id: "17138309-3dd0-45a4-8362-ea90e85c1eea",
        },
        {
          districtName: "Fortress",
          cost: "5",
          value: "5",
          type: "red",
          id: "c5069cda-aae6-44a0-8ef6-136d6291b785",
        },
        {
          districtName: "Prison",
          cost: "2",
          value: "2",
          type: "red",
          id: "d1c75181-645e-49b7-9957-919ba2781465",
        },
      ],
      character: {},
      districts: [],
      gold: 2,
      isAlive: true,
      isHost: true,
      isMarkedForTheft: false,
      isKing: false,
      id: "d8ZSvTzfstJVAmhVAAAJ",
      originalIndex: 0,
    },
    {
      userName: "sgsqn",
      cards: [
        {
          districtName: "Smithy",
          cost: "5",
          value: "5",
          type: "purple",
          uniqueDescription:
            "Once during your turn, you may pay 2 gold to draw 3 district cards.",
          abilityUsed: false,
          id: "e7d79ba9-cedb-4ee3-8c15-0411ad63c3b4",
        },
        {
          districtName: "Library",
          cost: "6",
          value: "6",
          type: "purple",
          uniqueDescription:
            "If you choose to draw cards when you take an action, you must keep an extra card you have drawn.",
          abilityUsed: false,
          id: "757f11c5-c290-492d-b715-a88a5d1c0535",
        },
        {
          districtName: "Watchtower",
          cost: "1",
          value: "1",
          type: "red",
          id: "31c14f5d-8706-401b-b846-32ec90fd3500",
        },
        {
          districtName: "Church",
          cost: "2",
          value: "2",
          type: "blue",
          id: "d1065675-1968-41df-87f6-e4e674f71ceb",
        },
      ],
      character: {},
      districts: [],
      gold: 2,
      isAlive: true,
      isHost: false,
      isMarkedForTheft: false,
      isKing: false,
      id: "wdG29YwhvUTQVuEWAAAL",
      originalIndex: 1,
    },
  ],
  deadCharacter: null,
  finalTurn: false,
  gameStarted: true,
  finishedFirst: "",
  host: "vqxrs",
  currentTurn: "vqxrs",
};

export default function finalScoreCalc(gameData) {
  let finalScoreData = [];

  // collect players
  // add points for finishing first
  // add points for completed city (make sure to not double dip first)
  // add points for 1 of each kind
  // add points for card values
}
